services:
  app:
    container_name: laravel_app_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:delegated
      - ./docker/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
      - app_vendor:/var/www/html/vendor
      - app_node:/var/www/html/node_modules
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
    ports:
      - "5173:5173"   # expose Vite
    networks:
      - appnet

  web:
    container_name: laravel_app_nginx
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - app
    networks:
      - appnet

  db:
    container_name: laravel_app_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:
  app_vendor:
  app_node:

networks:
  appnet:
    driver: bridge